import type { Song } from '../../types';
import type { ThemeConfig } from '../index';

const eurovision2026Songs: Song[] = [
  {
    id: 'al',
    header: 'Albania',
    icon: '🇦🇱',
    artist: 'Alis',
    song: 'Nân',
    youtubeUrl: 'https://youtu.be/b9AdRrA554o',
  },
  {
    id: 'am',
    header: 'Armenia',
    icon: '🇦🇲',
    artist: 'Simón',
    song: 'Paloma Rumba',
    youtubeUrl: 'https://youtu.be/5EXoK-lgocw',
  },
  {
    id: 'au',
    header: 'Australia',
    icon: '🇦🇺',
    artist: 'Delta Goodrem',
    song: 'Eclipse',
    youtubeUrl: 'https://youtu.be/EUMCr1pnaMY',
  },
  {
    id: 'at',
    header: 'Austria',
    icon: '🇦🇹',
    artist: 'Cosmó',
    song: 'Tanzschein',
    youtubeUrl: 'https://youtu.be/zPGP9ZphxiY',
  },
  {
    id: 'az',
    header: 'Azerbaijan',
    icon: '🇦🇿',
    artist: 'Jiva',
    song: 'Just Go',
    youtubeUrl: 'https://youtu.be/iMDBPe25JhM',
  },
  {
    id: 'be',
    header: 'Belgium',
    icon: '🇧🇪',
    artist: 'Essyla',
    song: 'Dancing on the Ice',
    youtubeUrl: 'https://youtu.be/9sfI4g6DWTU',
  },
  {
    id: 'bg',
    header: 'Bulgaria',
    icon: '🇧🇬',
    artist: 'Dara',
    song: 'Bangaranga',
    youtubeUrl: 'https://youtu.be/J3oGYo_mekw',
  },
  {
    id: 'hr',
    header: 'Croatia',
    icon: '🇭🇷',
    artist: 'Lelek',
    song: 'Andromeda',
    youtubeUrl: 'https://youtu.be/vl7Jqnw10sU',
  },
  {
    id: 'cy',
    header: 'Cyprus',
    icon: '🇨🇾',
    artist: 'Antigoni',
    song: 'Jalla',
    youtubeUrl: 'https://youtu.be/TzSs51BiQrE',
  },
  {
    id: 'cz',
    header: 'Czechia',
    icon: '🇨🇿',
    artist: 'Daniel Zizka',
    song: 'Crossroads',
    youtubeUrl: 'https://youtu.be/6ea25aRGpLo',
  },
  {
    id: 'dk',
    header: 'Denmark',
    icon: '🇩🇰',
    artist: 'Søren Torpegaard Lund',
    song: 'Før vi går hjem',
    youtubeUrl: 'https://youtu.be/xKzEP9dwoss',
  },
  {
    id: 'ee',
    header: 'Estonia',
    icon: '🇪🇪',
    artist: 'Vanilla Ninja',
    song: 'Too Epic to Be True',
    youtubeUrl: 'https://youtu.be/lOiWuol3t3o',
  },
  {
    id: 'fi',
    header: 'Finland',
    icon: '🇫🇮',
    artist: 'Linda Lampenius and Pete Parkkonen',
    song: 'Liekinheitin',
    youtubeUrl: 'https://youtu.be/9bfwNIYb96Q',
  },
  {
    id: 'fr',
    header: 'France',
    icon: '🇫🇷',
    artist: 'Monroe',
    song: 'Regarde !',
    youtubeUrl: 'https://youtu.be/ujoCYrvvTYQ',
  },
  {
    id: 'ge',
    header: 'Georgia',
    icon: '🇬🇪',
    artist: 'Bzikebi',
    song: 'On Replay',
    youtubeUrl: 'https://youtu.be/coh-lygCINY',
  },
  {
    id: 'de',
    header: 'Germany',
    icon: '🇩🇪',
    artist: 'Sarah Engels',
    song: 'Fire',
    youtubeUrl: 'https://youtu.be/AzvRc3eH_rA',
  },
  {
    id: 'gr',
    header: 'Greece',
    icon: '🇬🇷',
    artist: 'Akylas',
    song: 'Ferto',
    youtubeUrl: 'https://youtu.be/NGwNTd_DA9s',
  },
  {
    id: 'il',
    header: 'Israel',
    icon: '🇮🇱',
    artist: 'Noam Bettan',
    song: 'Michelle',
    youtubeUrl: 'https://youtu.be/xWCnWSoG8nI',
  },
  {
    id: 'it',
    header: 'Italy',
    icon: '🇮🇹',
    artist: 'Sal Da Vinci',
    song: 'Per sempre sì',
    youtubeUrl: 'https://youtu.be/V406FAGkhyQ',
  },
  {
    id: 'lv',
    header: 'Latvia',
    icon: '🇱🇻',
    artist: 'Atvara',
    song: 'Ēnā',
    youtubeUrl: 'https://youtu.be/6C2ivaB5D00',
  },
  {
    id: 'lt',
    header: 'Lithuania',
    icon: '🇱🇹',
    artist: 'Lion Ceccah',
    song: 'Sólo quiero más',
    youtubeUrl: 'https://youtu.be/0H-PXnbhG7A',
  },
  {
    id: 'lu',
    header: 'Luxembourg',
    icon: '🇱🇺',
    artist: 'Eva Marija',
    song: 'Mother Nature',
    youtubeUrl: 'https://youtu.be/DmVfJSRqgnI',
  },
  {
    id: 'mt',
    header: 'Malta',
    icon: '🇲🇹',
    artist: 'Aidan',
    song: 'Bella',
    youtubeUrl: 'https://youtu.be/CW6mQLBh6Js',
  },
  {
    id: 'md',
    header: 'Moldova',
    icon: '🇲🇩',
    artist: 'Satoshi',
    song: 'Viva, Moldova!',
    youtubeUrl: 'https://youtu.be/SViojHjNSzc',
  },
  {
    id: 'me',
    header: 'Montenegro',
    icon: '🇲🇪',
    artist: 'Tamara Živković',
    song: 'Nova zora',
    youtubeUrl: 'https://youtu.be/nuvy2d60HbI',
  },
  {
    id: 'no',
    header: 'Norway',
    icon: '🇳🇴',
    artist: 'Jonas Lovv',
    song: 'Ya Ya Ya',
    youtubeUrl: 'https://youtu.be/MasllzWk_bQ',
  },
  {
    id: 'pl',
    header: 'Poland',
    icon: '🇵🇱',
    artist: 'Alicja',
    song: 'Pray',
    youtubeUrl: 'https://youtu.be/q78cnYIoF9Y',
  },
  {
    id: 'pt',
    header: 'Portugal',
    icon: '🇵🇹',
    artist: 'Bandidos do Cante',
    song: 'Rosa',
    youtubeUrl: 'https://youtu.be/jyHaE6GqaaQ',
  },
  {
    id: 'ro',
    header: 'Romania',
    icon: '🇷🇴',
    artist: 'Alexandra Căpitănescu',
    song: 'Choke Me',
    youtubeUrl: 'https://youtu.be/yn0YmI0dPb8',
  },
  {
    id: 'sm',
    header: 'San Marino',
    icon: '🇸🇲',
    artist: 'Senhit',
    song: 'Superstar',
    youtubeUrl: 'https://youtu.be/wOQe-fQSFxg',
  },
  {
    id: 'rs',
    header: 'Serbia',
    icon: '🇷🇸',
    artist: 'Lavina',
    song: 'Kraj mene',
    youtubeUrl: 'https://youtu.be/FJTLKBOOE98',
  },
  {
    id: 'se',
    header: 'Sweden',
    icon: '🇸🇪',
    artist: 'Felicia',
    song: 'My System',
    youtubeUrl: 'https://youtu.be/ibbfS8iG450',
  },
  {
    id: 'ch',
    header: 'Switzerland',
    icon: '🇨🇭',
    artist: 'Veronica Fusaro',
    song: 'Alice',
    youtubeUrl: 'https://youtu.be/PfpYGAzW5dM',
  },
  {
    id: 'ua',
    header: 'Ukraine',
    icon: '🇺🇦',
    artist: 'Leléka',
    song: 'Ridnym',
    youtubeUrl: 'https://youtu.be/SoEXezpblAc',
  },
  {
    id: 'gb',
    header: 'United Kingdom',
    icon: '🇬🇧',
    artist: 'Look Mum No Computer',
    song: 'Eins, Zwei, Drei',
    youtubeUrl: 'https://youtu.be/niMKvJ-Itq8',
  },
];

export const eurovision2026Config: ThemeConfig = {
  id: 'eurovision2026',
  name: 'Eurovision Song Contest',
  description:
    'Europe\'s biggest music celebration returns! Rate and rank songs from 35 countries competing for the Eurovision crown in Vienna 2026. Big performances, bigger opinions.',
  year: '2026',
  style: {
    primaryBg: '#1a1a2e',
    secondaryBg: '#16213e',
    cardBg: '#2c3e50',
    textColor: '#e0e0e0',
    headerTextColor: '#ffffff',
    accentColor1: '#e94560',
    accentColor2: '#00f5d4',
    goldAccent: '#f9d71c',
  },
  songs: eurovision2026Songs,
};
